export const degreeCourseMap = {
  'Bachelor of Technology (BTech)': [
    'Computer Science and Engineering',
    'Electrical Engineering',
    'Mechanical Engineering',
    'Civil Engineering',
    'Metallurgical Engineering and Materials Science',
    'Chemical Engineering',
    'Mathematics and Computing',
    'Engineering Physics',
    'Space Science and Engineering (SSE)',
  ],
  'Master of Technology (MTech)': [
    'Electrical Engineering with specialization in Communication and Signal Processing',
    'Electrical Engineering with specialization in VLSI Design and Nanoelectronics',
    'Mechanical Engineering with specialization in Advanced Manufacturing (AM)',
    'Mechanical Engineering with specialization in Thermal Energy Systems (TES)',
    'Mechanical Engineering with specialization in Mechanical Systems Design',
    'Metallurgical Engineering and Materials Science with specialization in Materials Science and Engineering',
    'Metallurgical Engineering and Materials Science with specialization in Metallurgical Engineering',
    'M.Tech. in Electric Vehicle Technology',
    'M.Tech. in Space Engineering',
    'Computer Science and Engineering with specialization in Computer Science and Engineering',
    'Civil Engineering with specialization in Water, Climate and Sustainability',
    'Biosciences and Biomedical Engineering with specialization in Biomedical Engineering',
    'Mechanical Engineering with specialization in Applied Optics and laser Technology',
    'Civil Engineering with specialization in Structural Engineering',
    'Center of Futuristic Defence and Space Technology with specialization in Defence Technology',
    'Electrical Engineering with specialization in Power Systems and Power Electronics',
    'Biosciences and Biomedical Engineering with specialization in Biomedical Devices',
  ],
  'Master of Science (MSc)': [
    'Chemistry',
    'Physics',
    'Mathematics',
    'Biotechnology',
    'Astronomy',
  ],
  'BTech + MTech': [
    'BTech in Electrical Engineering with MTech in Communication and Signal Processing',
    'BTech in Electrical Engineering with MTech in VLSI Design and Nanoelectronics',
    'BTech in Mechanical Engineering with MTech in Production and Industrial Engineering',
    'BTech in Mechanical Engineering with MTech in Mechanical Systems Design',
  ],
  'MS(Research)': [
    'MS (Research) in Computer Science and Engineering',
    'MS (Research) in Electrical Engineering',
    'MS (Research) in Mechanical Engineering',
    'M.S. (Research) in Space Science and Engineering',
    'M.S. (Research) in Humanities and Social Sciences',
    'Master of Science in Data Science and Management (MS-DSM)',
  ],
  'Doctor of Philosophy': [
    'Computer Science and Engineering',
    'Electrical Engineering',
    'Mechanical Engineering',
    'Civil Engineering',
    'Metallurgical Engineering and Materials Science',
    'Bio-sciences and Bio-medical Engineering',
    'Chemistry',
    'Physics',
    'Mathematics',
    'English',
    'Philosophy',
    'Economics',
    'Psychology',
    'Sociology',
    'Astronomy, Astrophysics and Space Engineering',
    'Centre of Advanced Electronics',
    'Centre for Rural Development and Technology (CRDT)',
    'Center for Electric Vehicle and Intelligent Transport Systems (CEVITS)',
    'Center of Futuristic Defense and Space Technology (CFDST)',
    'JP Narayan National Center of Excellence in the Humanities',
    'Chemical Engineering',
  ],
  'M.A. ENGLISH': [
    'MA English (Literature and Linguistics)',
  ]
}; 